package com.example.hedgehog.kursach.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "COMMENTS".
 */
public class CommentsDao extends AbstractDao<Comments, Long> {

    public static final String TABLENAME = "COMMENTS";

    /**
     * Properties of entity Comments.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CommentId = new Property(0, Long.class, "commentId", true, "_id");
        public final static Property Comment = new Property(1, String.class, "comment", false, "COMMENT");
        public final static Property UserId = new Property(2, Long.class, "userId", false, "USER_ID");
        public final static Property FilmId = new Property(3, Long.class, "filmId", false, "FILM_ID");
    }

    private DaoSession daoSession;


    public CommentsDao(DaoConfig config) {
        super(config);
    }

    public CommentsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMMENTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: commentId
                "\"COMMENT\" TEXT NOT NULL ," + // 1: comment
                "\"USER_ID\" INTEGER," + // 2: userId
                "\"FILM_ID\" INTEGER);"); // 3: filmId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMMENTS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Comments entity) {
        stmt.clearBindings();
 
        Long commentId = entity.getCommentId();
        if (commentId != null) {
            stmt.bindLong(1, commentId);
        }
        stmt.bindString(2, entity.getComment());
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(3, userId);
        }
 
        Long filmId = entity.getFilmId();
        if (filmId != null) {
            stmt.bindLong(4, filmId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Comments entity) {
        stmt.clearBindings();
 
        Long commentId = entity.getCommentId();
        if (commentId != null) {
            stmt.bindLong(1, commentId);
        }
        stmt.bindString(2, entity.getComment());
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(3, userId);
        }
 
        Long filmId = entity.getFilmId();
        if (filmId != null) {
            stmt.bindLong(4, filmId);
        }
    }

    @Override
    protected final void attachEntity(Comments entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Comments readEntity(Cursor cursor, int offset) {
        Comments entity = new Comments( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // commentId
                cursor.getString(offset + 1), // comment
                cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // userId
                cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // filmId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Comments entity, int offset) {
        entity.setCommentId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setComment(cursor.getString(offset + 1));
        entity.setUserId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setFilmId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Comments entity, long rowId) {
        entity.setCommentId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Comments entity) {
        if (entity != null) {
            return entity.getCommentId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Comments entity) {
        return entity.getCommentId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUsersDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getFilmsDao().getAllColumns());
            builder.append(" FROM COMMENTS T");
            builder.append(" LEFT JOIN USERS T0 ON T.\"USER_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN FILMS T1 ON T.\"FILM_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Comments loadCurrentDeep(Cursor cursor, boolean lock) {
        Comments entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Users user = loadCurrentOther(daoSession.getUsersDao(), cursor, offset);
        entity.setUser(user);
        offset += daoSession.getUsersDao().getAllColumns().length;

        Films film = loadCurrentOther(daoSession.getFilmsDao(), cursor, offset);
        entity.setFilm(film);

        return entity;    
    }

    public Comments loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[]{key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Comments> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Comments> list = new ArrayList<Comments>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Comments> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }


    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Comments> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
